name: technicaltest_mobiledev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: 3.5.0
  firebase_core: 1.20.0
  firebase_storage: 10.2.10
  flutter:
    sdk: flutter
  fluttertoast: 8.0.9
  get: 4.6.5
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets: 
      - assets/images/
  uses-material-design: true
